name: Pull Request

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Code style check
    uses: ./.github/workflows/code_style_check.yml
  clang:
    name: Clang Analyzer
    needs:
      - style
    uses: ./.github/workflows/clang_analyzer.yml
  iwyu:
    name: IWYU
    needs:
      - style
    uses: ./.github/workflows/iwyu.yml
  android:
    name: Android
    needs:
      - msvc
    uses: ./.github/workflows/android.yml
